name: Tests

on: [push]

defaults:
  run:
    shell: bash

jobs:
  unit_testing:
    strategy:
      matrix:
        os: [ ubuntu-24.04 ]  #  windows-latest, macos-12,
        py: [ "3.11", "3.12" ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4.1.7
    - name: Install System Dependencies
      run: sudo apt install gir1.2-appindicator3-0.1 libgirepository1.0-dev libcairo2-dev gobject-introspection gir1.2-gtk-3.0 python-gi-dev gir1.2-gdkpixbuf-2.0
    - name: Set up Python
      uses: actions/setup-python@v5.1.0
      with:
        python-version: ${{ matrix.py }}
    - name: Install Pip Dependencies from Requirements
      run: pip install -r requirements.txt
    - name: Run Tests
      run: coverage run -m pytest && coverage report -m
    - name: Coveralls
      if: ${{ matrix.os == 'ubuntu-24.04' }}
      run: coveralls --service=github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
